.MODEL SMALL
.STACK 100H
.DATA

MSG1 DB 'ENTER A LOWER CASE LETTER: $'   
MSG2 DB 13,10, 'IN UPPER CASE IT IS: $'  
CHAR DB ?  
.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    
    LEA DX,MSG1
    MOV AH,9
    INT 21H
    
    MOV AH,1
    INT 21H
    SUB AL,20H   ;LOWER TO HIGHER
    MOV CHAR,AL  ;TO SAVE IT
    
    LEA DX,MSG2
    MOV AH,9
    INT 21H
    
    MOV AH,2
    MOV DL,CHAR   ;PRINT THE CHARACTER IN HIGTHER CASE
    INT 21H

    MOV AH,4CH
    INT 21H
    
    
MAIN ENDP
END MAIN